In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)

n = 2000

df = pd.DataFrame({
    "account_id": range(1, n+1),
    "dpd": np.random.randint(30, 180, n),
    "outstanding_balance": np.random.randint(20000, 500000, n),
    "customer_income": np.random.randint(20000, 150000, n),
    "previous_payments": np.random.randint(0, 10, n),
    "collection_attempts": np.random.randint(0, 6, n),
    "region": np.random.choice(["North","South","East","West"], n),
    "employment_type": np.random.choice(["Salaried","Self-employed","Business"], n)
})

In [5]:
df.head()

,account_id,dpd,outstanding_balance,customer_income,previous_payments,collection_attempts,region,employment_type
0,1,132,31871,79234,7,2,South,Business
1,2,122,245371,45851,5,1,East,Salaried
2,3,44,228524,51279,9,4,North,Self-employed
3,4,136,225342,137431,8,5,South,Self-employed
4,5,101,184685,116063,6,3,West,Business

In [6]:
df["recovered_flag"] = (
    (df["dpd"] < 90) &
    (df["previous_payments"] > 3)
).astype(int)

In [7]:
df.head()

,account_id,dpd,outstanding_balance,customer_income,previous_payments,collection_attempts,region,employment_type,recovered_flag
0,1,132,31871,79234,7,2,South,Business,0
1,2,122,245371,45851,5,1,East,Salaried,0
2,3,44,228524,51279,9,4,North,Self-employed,1
3,4,136,225342,137431,8,5,South,Self-employed,0
4,5,101,184685,116063,6,3,West,Business,0

In [9]:
df.to_csv(r"C:\Users\user\Desktop\Data bricks\ML\collection-recovery-project\Dataset\Dataset-generation.csv",index= False)